I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 407, in script
    scene bg black with face
  File "game/script.rpy", line 407, in <module>
    scene bg black with face
NameError: name 'face' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 407, in script
    scene bg black with face
  File "/Applications/renpy-6.99.3-sdk/renpy/ast.py", line 1232, in execute
    paired = renpy.python.py_eval(self.paired)
  File "/Applications/renpy-6.99.3-sdk/renpy/python.py", line 1479, in py_eval
    return eval(py_compile(source, 'eval'), globals, locals)
  File "game/script.rpy", line 407, in <module>
    scene bg black with face
NameError: name 'face' is not defined

Darwin-14.3.0-x86_64-i386-64bit
Ren'Py 6.99.3.404
Build A Bara 0.0
